//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID_Task { get; set; }
        public string Title_Task { get; set; }
        public int ID_Type { get; set; }
        public string Info { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
